#!/bin/bash
#PBS -N playTopics
#PBS -l select=1:ncpus=8:mem=30gb,walltime=24:00:00
#PBS -M jsybran@clemson.edu
#PBS -m ea

EXP_NAME=play
SOURCE_LBL="torcetrapib"
TARGET_LBL="high_blood_pressure"
NUM_TOPICS=20

module load gcc mpich2/1.4-eth

# Place us in the working directory
if [ -z "$PBS_O_WORKDIR" ]; then
  echo "Must be submitted through PBS from home directory"
  exit 1
fi
cd $PBS_O_WORKDIR

# Identify the project home dir
if [ -z "$PROJ_HOME" ]; then
  echo "searching for moliere home directory"
  PROJ_HOME=$(pwd | grep -o .*moliere)
  if [ "$PROJ_HOME" = "" ]; then
    echo "Failed to find project home"
    exit 1
  else
    echo "Found $PROJ_HOME"
  fi
fi

# add project tools to path
PATH=$PATH:$PROJ_HOME/tools/plda

RES=$PROJ_HOME/results/$EXP_NAME
BAG_DIR=$RES/DATA
MODEL_DIR=$RES/MODEL
VIEW_DIR=$RES/VIEW

mkdir -p $MODEL_DIR
mkdir -p $VIEW_DIR

HYPO_NAME="$TARGET_LBL---$SOURCE_LBL"
BAG_FILE="$BAG_DIR/$HYPO_NAME"
MODEL_FILE="$MODEL_DIR/$HYPO_NAME"
VIEW_FILE="$VIEW_DIR/$HYPO_NAME"

mpiexec -n 8 mpi_lda --num_topics $NUM_TOPICS \
                     --alpha 1 \
                     --beta 0.01 \
                     --training_data_file $BAG_FILE \
                     --model_file $MODEL_FILE \
                     --total_iterations 1000 \
                     --burn_in_iterations 100
view_model.py "$MODEL_FILE"'_0' $VIEW_FILE
