#!/bin/bash
#PBS -N playTopics
#PBS -l select=1:ncpus=8:mem=30gb,walltime=24:00:00
#PBS -M jsybran@clemson.edu
#PBS -m ea

EXP_NAME=play
SOURCE_LBL="htr1a"
TARGET_LBL="venlafaxine"

module load gcc mpich2/1.4-eth

# Place us in the working directory
if [ -z "$PBS_O_WORKDIR" ]; then
  echo "Must be submitted through PBS from home directory"
  exit 1
fi
cd $PBS_O_WORKDIR

# Identify the project home dir
if [ -z "$PROJ_HOME" ]; then
  echo "searching for moliere home directory"
  PROJ_HOME=$(pwd | grep -o .*moliere)
  if [ "$PROJ_HOME" = "" ]; then
    echo "Failed to find project home"
    exit 1
  else
    echo "Found $PROJ_HOME"
  fi
fi

# add project tools to path
PATH=$PATH:$PROJ_HOME/tools/plda

DATA=$PROJ_HOME/data
NET=$DATA/network
VECS=$DATA/fastText
TEXT=$DATA/processedText
RES=$PROJ_HOME/results/$EXP_NAME

BAG="$RES/DATA/$SOURCE_LBL---$TARGET_LBL"
MODEL=$RES/MODEL
VIEW=$RES/VIEW

mkdir -p $MODEL
mkdir -p $VIEW

for BAG_FILE in $(ls -f $BAG);do
  if [ ! -f $VIEW_DIR/$BAG_FILE ] && [ -f $BAG_FILE]; then
    in=$BAG/$BAG_FILE
    out=$MODEL/$BAG_FILE
    mpiexec -n 8 mpi_lda --num_topics $NUM_TOPICS \
                         --alpha 1 \
                         --beta 0.01 \
                         --training_data_file $in \
                         --model_file $out \
                         --total_iterations 500 \
                         --burn_in_iterations 50 \
                         > /dev/null 2>&1
    view_model.py "$MODEL/$BAG_FILE"'_0' $VIEW/$BAG_FILE
  fi
done
