#!/bin/bash
#PBS -N playProfile
#PBS -l select=1:ncpus=8:mem=60gb,walltime=24:00:00
#PBS -M jsybran@clemson.edu
#PBS -m ea

module load gcc gnu-parallel openmpi

EXP_NAME=play
SOURCE_LBL="torcetrapib"
TARGET_LBL="high_blood_pressure"

# Place us in the working directory
if [ -z "$PBS_O_WORKDIR" ]; then
  echo "Must be submitted through PBS from home directory"
  exit 1
fi
cd $PBS_O_WORKDIR

# Identify the project home dir
if [ -z "$PROJ_HOME" ]; then
  echo "searching for moliere home directory"
  PROJ_HOME=$(pwd | grep -o .*moliere)
  if [ "$PROJ_HOME" = "" ]; then
    echo "Failed to find project home"
    exit 1
  else
    echo "Found $PROJ_HOME"
  fi
fi

# add project tools to path
PATH=$PATH:$PROJ_HOME/code/components/links

HYPO_NAME="$TARGET_LBL---$SOURCE_LBL"

RES=$PROJ_HOME/results/$EXP_NAME/2016
VIEW_DIR=$RES/VIEW
VIEW_FILE="$VIEW_DIR/$HYPO_NAME"

#DATA=$PROJ_HOME/data/yearlySubsets/2010
DATA=$PROJ_HOME/data
FAST_TEXT=$DATA/fastText
CUID_VEC=$FAST_TEXT/umls.data
NGRAM_VEC=$FAST_TEXT/canon.vec

OUT=$RES/$HYPO_NAME.profile

evalHybrid -m $VIEW_FILE \
           -n $NGRAM_VEC \
           -c $CUID_VEC \
           -s $SOURCE_LBL \
           -t $TARGET_LBL \
           -P "0 1.5203 .29332 1.9804 .87312 2.2369 .38104 1.0092" \
           -r 20 \
           > $OUT

