#!/bin/bash
module load gcc
module load openmpi
PROJ_HOME=$(pwd | grep -o .*moliere)

clear
rm -rf bin
mkdir bin
g++ *.cpp -O2 -Wall -o ./bin/evalPredicate -I$PROJ_HOME/code/components/sharedHeaders
ln -sf ./bin/evalPredicate

