#!/bin/bash
#########
#
# CONSIDER THIS TO BE AN EXAMPLE
#
#########
module load gcc mpich2/1.4-eth
IN_FILE=$1
OUT_FILE=$2
echo $IN_FILE
echo $OUT_FILE
mpiexec mpi_lda --num_topics 20 --alpha 1 --beta 0.01 --training_data_file $IN_FILE --model_file $OUT_FILE --total_iterations 100 --burn_in_iterations 50

