#!/bin/bash
module load gcc
module load openmpi

PROJ_HOME=$(pwd | grep -o .*moliere)

clear
rm -rf bin
mkdir bin
g++ *.cpp -O3 -Wall -o ./bin/evalWithEmbeddings -fopenmp -I$PROJ_HOME/code/components/sharedHeaders
ln -sf ./bin/evalWithEmbeddings

