#!/bin/bash
module load gcc
module load openmpi

PROJ_HOME=$(pwd | grep -o .*moliere)
clear
rm -rf bin
mkdir bin
g++ *.cpp -fopenmp -g -Wall -o ./bin/evalHybrid -I$PROJ_HOME/code/components/sharedHeaders
ln -sf ./bin/evalHybrid

